=== alesiahlushakova/EPAMJava/task4Web/data/Medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/Medicines"
        xmlns:tns="http://www.example.com/Medicines"
        elementFormDefault="qualified">


    <element name="Medicines">
        <complexType>
            <sequence>
                <element ref="tns:Medicine" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <!-- entities -->
    <element name="Medicine"   type="tns:Medicine"   abstract="true"/>
    <element name="Antibiotic" type="tns:Antibiotic" substitutionGroup="tns:Medicine"/>
    <element name="Vitamin"    type="tns:Vitamin"    substitutionGroup="tns:Medicine"/>
    <element name="Analgetic"  type="tns:Analgetic"  substitutionGroup="tns:Medicine"/>

    <!-- type definition for abstract Medicine  -->
    <complexType name="Medicine">
        <sequence>
            <element name="Pharm" type="string"/>
            <element name="Version" type="tns:Version" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="name" use="required">
            <simpleType>
                <restriction base="string">
                    <whiteSpace value="collapse"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="CAS" use="required">
            <simpleType>
                <restriction base="string">
                    <pattern value="([0-9]{2,5})-([0-9]{2})-([0-9]{1})"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="drug_bank" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="DB([0-9]{5})"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <!--  Antibiotic element -->
    <complexType name="Antibiotic">
        <complexContent>
            <extension base="tns:Medicine">
                <attribute name="recipe" type="boolean" default="true"/>
            </extension>
        </complexContent>
    </complexType>

    <!-- Vitamin element -->
    <complexType name="Vitamin">
        <complexContent>
            <extension base="tns:Medicine">
                <attribute name="solution" use="optional">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="water"/>
                            <enumeration value="fat"/>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

    <!--  Analgetic element -->
    <complexType name="Analgetic">
        <complexContent>
            <extension base="tns:Medicine">
                <attribute name="narcotic" type="boolean" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <!--  Version element -->
    <complexType name="Version">
        <sequence>
            <element name="Producer" type="string"/>
            <element name="Form">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="tablet"  />
                        <enumeration value="pills" />
                        <enumeration value="powder"/>
                        <enumeration value="liquid"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="Certificate" type="tns:Certificate"/>
            <element name="Package" type="tns:Package" minOccurs="1" maxOccurs="unbounded"/>
            <element name="Dosage" type="tns:Dosage"/>
        </sequence>
        <attribute name="analog" type="string" use="required"/>
    </complexType>

    <!-- tCertificate element -->
    <complexType name="Certificate">
        <sequence>
            <element name="Registered_by" type="string"/>
            <element name="Registration_date">
                <simpleType>
                    <restriction base="date">
                        <minInclusive value="2000-01-01"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="Expiration_date">
                <simpleType>
                    <restriction base="date">
                        <maxInclusive value="2029-01-01"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <!-- Package element -->
    <complexType name="Package">
        <sequence>
            <element name="Quantity" type="positiveInteger"/>
            <element name="Price"  type="double"/>
        </sequence>
        <attribute name="size" use="optional">
            <simpleType>
                <restriction base="string">
                    <enumeration value="small"></enumeration>
                    <enumeration value="medium"></enumeration>
                    <enumeration value="large"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <!-- Dosage element -->
    <complexType name="Dosage">
        <sequence>
            <element name="Amount" type="string"/>
            <element name="Frequency" type="string"/>
        </sequence>
    </complexType>
</schema>

=== alesiahlushakova/EPAMJava/task4Web/web/xml/Medicines.xml
<?xml version="1.0" encoding="UTF-8"?>
<Medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/Medicines"
          xsi:schemaLocation="Medicines.xsd">
    <Vitamin name="Retinol" CAS="68-26-8" drug_bank="DB00162" solution="fat">
        <Pharm>Scientists</Pharm>
        <Version analog="Retinol Serum">
            <Producer>Daumann</Producer>
            <Form>liquid</Form>
            <Certificate>
                <Registered_by>Special Committee of Experts of the General Secretariat of Research and Technology</Registered_by>
                <Registration_date>2009-07-12</Registration_date>
                <Expiration_date>2020-09-20</Expiration_date>
            </Certificate>
            <Package>
                <Quantity>60</Quantity>
                <Price>14.95</Price>
            </Package>
            <Dosage>
                <Amount>1 ml</Amount>
                <Frequency>2/day</Frequency>
            </Dosage>
        </Version>
    </Vitamin>
    <Antibiotic name="Amoxicillin" CAS="26787-78-0" drug_bank="DB01060" recipe="false">
        <Pharm>Beecham</Pharm>
        <Version analog="Amoxisar">
            <Producer>Chemical Inc.</Producer>
            <Form>powder</Form>
            <Certificate>
                <Registered_by>UK Health department</Registered_by>
                <Registration_date>2015-11-15</Registration_date>
                <Expiration_date>2020-11-14</Expiration_date>
            </Certificate>
            <Package>
                <Quantity>60</Quantity>
                <Price>3.05</Price>
            </Package>
            <Dosage>
                <Amount>1 vial</Amount>
                <Frequency>3/day</Frequency>
            </Dosage>
        </Version>
        <Version analog="Moxatag">
            <Producer>Vernalis therapeutic</Producer>
            <Form>tablet</Form>
            <Certificate>
                <Registered_by>Specialty Pharmacy Certification Board</Registered_by>
                <Registration_date>2010-03-18</Registration_date>
                <Expiration_date>2021-04-17</Expiration_date>
            </Certificate>
            <Package size="small">
                <Quantity>10</Quantity>
                <Price>172.46</Price>
            </Package>
            <Package size="medium">
                <Quantity>30</Quantity>
                <Price>501.25</Price>
            </Package>
            <Dosage>
                <Amount>1 tablet</Amount>
                <Frequency>1/day</Frequency>
            </Dosage>
        </Version>
    </Antibiotic>
    <Analgetic name="Ibuprofen" CAS="15687-27-1" drug_bank="DB01050" narcotic="false">
        <Pharm>Stewart Adams</Pharm>
        <Version analog="Neurofen">
            <Producer>Reckitt Benckiser</Producer>
            <Form>tablet</Form>
            <Certificate>
                <Registered_by>FDA</Registered_by>
                <Registration_date>2015-09-10</Registration_date>
                <Expiration_date>2028-10-10</Expiration_date>
            </Certificate>
            <Package size="small">
                <Quantity>6</Quantity>
                <Price>7.99</Price>
            </Package>
            <Package size="medium">
                <Quantity>8</Quantity>
                <Price>9.11</Price>
            </Package>
            <Package size="large">
                <Quantity>12</Quantity>
                <Price>11.12</Price>
            </Package>
            <Dosage>
                <Amount>1 tablet</Amount>
                <Frequency>3-4/day</Frequency>
            </Dosage>
        </Version>
    </Analgetic>
</Medicines>
